version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.20
  build:
    commands:
      - export GO111MODULE=on && go test github.com/vimiomori/aws-secretsmanager-caching-go-v2/secretcache -v
      - export GO111MODULE=on && go test github.com/vimiomori/aws-secretsmanager-caching-go-v2/scintegtests -v
